version: '3'
services:
  pyspark:
    image: "jupyter/pyspark-notebook"
    command: /usr/local/bin/start-notebook.sh --NotebookApp.password='' --NotebookApp.notebook_dir=/jupyter/
    volumes:
      - ./data:/jupyter/data
      - ./src:/jupyter/src
    ports:
      - 8891:8888